name-template: $NEXT_MINOR_VERSION
tag-template: v$NEXT_MINOR_VERSION

categories:
  - title: ðŸš€ New features and improvements
    labels:
      - enhancement
  - title: ðŸ› Bug Fixes
    labels:
      - bug
  - title: ðŸš¦ Internal changes
    labels:
      - internal

exclude-labels:
  - no-changelog
  - duplicate
  - invalid

template: |
    $CHANGES

    Prebuilt version available from [here](https://repo.gradle.org/gradle/ext-releases-local/org/gradle/profiler/gradle-profiler/$NEXT_MINOR_VERSION/gradle-profiler-$NEXT_MINOR_VERSION.zip)

    Install Gradle profiler $NEXT_MINOR_VERSION with [SDKMAN!](http://sdkman.io/):

        > sdk install gradleprofiler $NEXT_MINOR_VERSION
