package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("gradleprofiler.sdkman.key", "credentialsJSON:a76beba1-f1a3-44c6-9995-9808bf652c9e", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("gradleprofiler.sdkman.key", "credentialsJSON:28e1a1ff-4594-4972-824c-5c3cdcaefc05", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("gradleprofiler.sdkman.token", "credentialsJSON:518893d3-6327-427f-a63f-b12b94399315", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("gradleprofiler.sdkman.token", "credentialsJSON:a8c19c49-5e95-408c-bc5f-4f89c9c4c24c", display = ParameterDisplay.HIDDEN)
        }
    }
}
