use ahash::{AHashMap, AHashSet};

use crate::WasmStackGraph;

fn build_children_csr(
    node_names: &[String],
    children: &[AHashMap<String, usize>],
) -> (Vec<i32>, Vec<i32>) {
    let size = node_names.len();
    let mut children_offsets: Vec<i32> = Vec::with_capacity(size + 1);
    let mut children_data: Vec<i32> = Vec::new();

    for i in 0..size {
        children_offsets.push(children_data.len() as i32);
        let child_map = &children[i];
        if !child_map.is_empty() {
            let mut ids: Vec<usize> = child_map.values().copied().collect();
            ids.sort_unstable_by(|&a, &b| node_names[a].cmp(&node_names[b]));
            for id in ids {
                children_data.push(id as i32);
            }
        }
    }
    children_offsets.push(children_data.len() as i32);

    (children_offsets, children_data)
}

struct ParsedName<'a> {
    simple_class_name: &'a str,
    method_name: &'a str,
    /// Java source-style parameter list (e.g. `java.lang.String, int[]`), as produced by the JFR
    /// format. Async-profiler parsers always set this to `None`
    raw_params: Option<&'a str>,
    method_location: Option<&'a str>,
}

/// Format: `org.example.ClassName.methodName(params):line_[j]`
/// Generated by org.gradle.profiler.flamegraph.JfrToStacksConverter
fn parse_method_name_jfr(name: &str) -> Option<ParsedName<'_>> {
    let paren_open = name.find('(')?;
    let paren_close = name[paren_open..].find(')').map(|i| paren_open + i)?;
    let method_name_separator = name[..paren_open].rfind('.')?;

    let class_name = &name[..method_name_separator];
    if class_name.is_empty() {
        return None;
    }

    let method_name = &name[method_name_separator + 1..paren_open];
    if method_name.is_empty() {
        return None;
    }

    let class_name_start = class_name.rfind('.').map_or(0, |i| i + 1);
    let simple_class_name = &class_name[class_name_start..];
    if simple_class_name.is_empty() {
        return None;
    }

    let raw_params = &name[paren_open + 1..paren_close];
    let after_paren = &name[paren_close + 1..];
    let rest = after_paren.strip_suffix("_[j]").unwrap_or(after_paren);
    let line_number = rest.strip_prefix(':').filter(|s| !s.is_empty());

    Some(ParsedName { simple_class_name, method_name, raw_params: Some(raw_params), method_location: line_number })
}

/// Format: `org/example/ClassName.methodName_[type]`
/// Generated by https://github.com/async-profiler/async-profiler/blob/e1dd4c05f654c96691ef140842aceeb31ee0150e/src/frameName.cpp
fn parse_method_name_async_profiler(name: &str) -> Option<ParsedName<'_>> {
    let last_part = name.rfind('/').map_or(name, |i| &name[i + 1..]);
    let class_name_end = last_part.find('.')?;

    let simple_class_name = &last_part[..class_name_end];
    if simple_class_name.is_empty() {
        return None;
    }

    // Require _[type] suffix, e.g. _[0], _[j]
    let after_class_name = &last_part[class_name_end + 1..];
    if !after_class_name.ends_with(']') {
        return None;
    }
    let bci_start = after_class_name.rfind("_[")?;
    let frame_type = &after_class_name[bci_start + 2..after_class_name.len() - 1];
    if frame_type.is_empty() {
        return None;
    }

    let method_name = &after_class_name[..bci_start];
    if method_name.is_empty() {
        return None;
    }

    Some(ParsedName { simple_class_name, method_name, raw_params: None, method_location: Some(frame_type ) })
}

fn parse_method_name(name: &str) -> Option<ParsedName<'_>> {
    parse_method_name_jfr(name).or_else(|| parse_method_name_async_profiler(name))
}

fn simplify_jfr_param(param: &str) -> &str {
    let trimmed = param.trim();
    let base_end = trimmed.find('[')
        .or_else(|| trimmed.ends_with("...").then(|| trimmed.len() - 3))
        .unwrap_or(trimmed.len());
    trimmed[..base_end].rfind('.').map_or(trimmed, |i| &trimmed[i + 1..])
}

fn format_display_name(p: &ParsedName, show_params: bool, show_line: bool) -> String {
    let capacity = p.simple_class_name.len() + 1 + p.method_name.len()
        + if show_params { 1 + p.raw_params.map_or(0, |raw| raw.len()) + 1 } else { 0 }
        + if show_line { p.method_location.map_or(0, |ln| ln.len() + 1) } else { 0 };

    let mut s = String::with_capacity(capacity);
    s.push_str(p.simple_class_name);
    s.push('.');
    s.push_str(p.method_name);
    if show_params {
        s.push('(');
        p.raw_params.into_iter()
            .flat_map(|params| params.split(',').map(simplify_jfr_param))
            .enumerate()
            .for_each(|(i, param)| {
                if i > 0 {
                    s.push_str(", ");
                }
                s.push_str(param);
            });
        s.push(')');
    }
    if show_line {
        if let Some(ln) = p.method_location {
            s.push(':');
            s.push_str(ln);
        }
    }
    s
}

fn compute_display_names(node_names: &[String]) -> Vec<String> {
    let parsed_names: Vec<(&str, Option<ParsedName<'_>>)> = node_names.iter()
        .map(|n| (n.as_str(), parse_method_name(n)))
        .collect();

    let mut first_params: AHashMap<(&str, &str), Option<&str>> = AHashMap::new();
    let mut first_location: AHashMap<(&str, &str, Option<&str>), Option<&str>> = AHashMap::new();
    for (_, parsed) in &parsed_names {
        if let Some(p) = parsed {
            first_params.entry((p.simple_class_name, p.method_name)).or_insert(p.raw_params);
            first_location.entry((p.simple_class_name, p.method_name, p.raw_params)).or_insert(p.method_location);
        }
    }

    let overloaded: AHashSet<(&str, &str)> = parsed_names.iter()
        .filter_map(|(_, parsed)| parsed.as_ref())
        .filter(|p| first_params[&(p.simple_class_name, p.method_name)] != p.raw_params)
        .map(|p| (p.simple_class_name, p.method_name))
        .collect();

    let ambiguous_location: AHashSet<(&str, &str, Option<&str>)> = parsed_names.iter()
        .filter_map(|(_, parsed)| parsed.as_ref())
        .filter(|p| first_location[&(p.simple_class_name, p.method_name, p.raw_params)] != p.method_location)
        .map(|p| (p.simple_class_name, p.method_name, p.raw_params))
        .collect();

    parsed_names
        .into_iter()
        .map(|(name, p)| {
            match p {
                Some(p) => {
                    let show_params = overloaded.contains(&(p.simple_class_name, p.method_name));
                    let show_line = ambiguous_location.contains(&(p.simple_class_name, p.method_name, p.raw_params));
                    format_display_name(&p, show_params, show_line)
                },
                None => return name.to_string(),
            }
        })
        .collect()
}

fn encode_strings<S: AsRef<str>>(strings: &[S]) -> (Vec<u8>, Vec<i32>) {
    let total_bytes: usize = strings.iter().map(|s| s.as_ref().len()).sum();
    let mut data: Vec<u8> = Vec::with_capacity(total_bytes);
    let mut offsets: Vec<i32> = Vec::with_capacity(strings.len() + 1);
    for s in strings {
        offsets.push(data.len() as i32);
        data.extend_from_slice(s.as_ref().as_bytes());
    }
    offsets.push(data.len() as i32);
    (data, offsets)
}

/// An append-only stack graph builder used to accumulate stacks before converting
/// to the flat `WasmStackGraph` format for transfer to JS.
pub(crate) struct GraphBuilder {
    /// children[i] maps child name → child node id
    pub(crate) children: Vec<AHashMap<String, usize>>,
    /// node_names[i] is the name of node i
    pub(crate) node_names: Vec<String>,
    /// values[i] is the number of samples for node i
    pub(crate) values: Vec<i64>,
}

impl GraphBuilder {
    pub(crate) fn new(root_name: &str) -> Self {
        GraphBuilder {
            children: vec![AHashMap::new()],
            node_names: vec![root_name.to_string()],
            values: vec![0],
        }
    }

    /// Returns `(node_id, was_created)`.
    pub(crate) fn get_or_create_child(&mut self, parent: usize, name: &str, weight: i64) -> (usize, bool) {
        if let Some(&id) = self.children[parent].get(name) {
            self.values[id] += weight;
            return (id, false);
        }
        let id = self.node_names.len();
        self.node_names.push(name.to_string());
        self.children.push(AHashMap::new());
        self.values.push(weight);
        self.children[parent].insert(name.to_string(), id);
        (id, true)
    }

    pub(crate) fn into_wasm_stack_graph(self) -> WasmStackGraph {
        let (children_offsets, children_data) = build_children_csr(&self.node_names, &self.children);
        let display_names = compute_display_names(&self.node_names);
        let (names_data, names_offsets) = encode_strings(&self.node_names);
        let (display_names_data, display_names_offsets) = encode_strings(&display_names);

        WasmStackGraph {
            children_offsets,
            children_data,
            names_data,
            names_offsets,
            display_names_data,
            display_names_offsets,
            values: self.values,
        }
    }
}
