package org.gradle.profiler.flamegraph;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Base64;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.zip.GZIPInputStream;

/**
 * Test fixtures useful for verifying content of files generated by {@link FlamegraphGenerator}.
 */
public class FlamegraphGeneratorTestFixture {

    private static final Base64.Decoder DECODER = Base64.getDecoder();

    private static final byte[] NAMES_TEMPLATE_TAG =
        "<template id=\"embedded-stacks-names\">".getBytes(StandardCharsets.UTF_8);

    /**
     * Assert that all given stacks files, and no others, are embedded in the given flamegraph HTML file.
     *
     * @param flamegraphHtml path to the flamegraph HTML file
     * @param stacksFiles paths to the stacks files to check for
     */
    public static void assertHasStacksFiles(Path flamegraphHtml, Collection<Path> stacksFiles) {
        assertHasStacksFiles(flamegraphHtml, stacksFiles, true);
    }

    /**
     * Asserts that all given stacks files are embedded in the given flamegraph HTML file.
     * <p>
     * When {@code strict} is true, the flamegraph must contain exactly the given stacks
     * files and no others. When {@code strict} is false, the flamegraph may contain
     * additional stacks files beyond those specified, but all given files must be present with
     * matching content.
     *
     * @param flamegraphHtml path to the flamegraph HTML file
     * @param stacksFiles paths to the stacks files to check for
     * @param strict if true, no extra stacks files are permitted; if false, extra files are allowed
     */
    public static void assertHasStacksFiles(Path flamegraphHtml, Collection<Path> stacksFiles, boolean strict) {
        List<String> embeddedNames = getEmbeddedStackFileNames(flamegraphHtml);
        Set<String> expectedNames = stacksFiles.stream().map(x -> x.getFileName().toString()).collect(Collectors.toSet());
        if (strict) {
            assert expectedNames.equals(new HashSet<>(embeddedNames)) : "Expected stacks files " + expectedNames + " but found " + embeddedNames;
        } else {
            assert new HashSet<>(embeddedNames).containsAll(expectedNames) : "Expected stacks files " + expectedNames + " but found " + embeddedNames;
        }

        for (int i = 0; i < embeddedNames.size(); i++) {
            String embeddedName = embeddedNames.get(i);
            Path expectedFile = stacksFiles.stream()
                .filter(x -> x.getFileName().toString().equals(embeddedName))
                .findFirst().orElse(null);
            if (expectedFile == null) {
                continue;
            }
            assert embeddedStackFileHasContent(flamegraphHtml, i, expectedFile) : "Stacks file " + embeddedName + " does not match expected content";
        }
    }

    /**
     * Returns the names of the stacks files embedded in the given flamegraph HTML file,
     * in the order they were embedded.
     *
     * @param flamegraphHtml path to the flamegraph HTML file
     *
     * @return the embedded stacks file names, or an empty list if none are found
     */
    private static List<String> getEmbeddedStackFileNames(Path flamegraphHtml) {
        try (BufferedInputStream input = new BufferedInputStream(Files.newInputStream(flamegraphHtml))) {
            LineBuffer line = new LineBuffer();
            while (line.readFrom(input)) {
                if (line.trimmedEquals(NAMES_TEMPLATE_TAG)) {
                    if (!line.readFrom(input)) {
                        break;
                    }
                    String namesBase64 = line.trimmedString(StandardCharsets.UTF_8);
                    if (namesBase64.isEmpty()) {
                        return List.of();
                    }
                    return Arrays.stream(namesBase64.split(","))
                        .map(s -> new String(DECODER.decode(s), StandardCharsets.UTF_8))
                        .collect(Collectors.toList());
                }
            }
            return List.of();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Returns true if the stacks data embedded at {@code index} in the given flamegraph HTML file
     * matches the content of {@code content}.
     *
     * @param flamegraphHtml path to the flamegraph HTML file
     * @param index index of the embedded stacks entry to check
     * @param content path to the original stacks file to compare against
     *
     * @return true if the embedded data equals the content of {@code content}
     */
    private static boolean embeddedStackFileHasContent(Path flamegraphHtml, int index, Path content) {
        byte[] templateTag = ("<template id=\"embedded-stacks-" + index + "\">").getBytes(StandardCharsets.UTF_8);
        try (BufferedInputStream input = new BufferedInputStream(Files.newInputStream(flamegraphHtml))) {
            LineBuffer line = new LineBuffer();
            while (line.readFrom(input)) {
                if (line.trimmedEquals(templateTag)) {
                    try (InputStream base64 = DECODER.wrap(new NewlineTerminatedInputStream(input));
                         GZIPInputStream gzip = new GZIPInputStream(base64);
                         InputStream expected = new BufferedInputStream(Files.newInputStream(content))
                    ) {
                        return streamsEqual(gzip, expected);
                    }
                }
            }
            return false;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static boolean streamsEqual(InputStream a, InputStream b) throws IOException {
        byte[] bufA = new byte[8192];
        byte[] bufB = new byte[8192];
        while (true) {
            int nA = a.readNBytes(bufA, 0, bufA.length);
            int nB = b.readNBytes(bufB, 0, bufB.length);
            if (nA != nB) {
                return false;
            }
            if (nA == 0) {
                return true;
            }
            if (!Arrays.equals(bufA, 0, nA, bufB, 0, nB)) {
                return false;
            }
        }
    }

    /**
     * Wraps an {@link InputStream}, stopping at the first newline character without
     * consuming the rest of the underlying stream.
     */
    private static class NewlineTerminatedInputStream extends InputStream {

        private final InputStream delegate;
        private boolean done;

        NewlineTerminatedInputStream(InputStream delegate) {
            this.delegate = delegate;
        }

        @Override
        public int read() throws IOException {
            if (done) {
                return -1;
            }
            int b = delegate.read();
            if (b == -1 || b == '\n') {
                done = true;
                return -1;
            }
            return b;
        }

        @Override
        public int read(byte[] buf, int off, int len) throws IOException {
            if (done) {
                return -1;
            }
            int count = 0;
            while (count < len) {
                int b = read();
                if (b == -1) {
                    break;
                }
                buf[off + count++] = (byte) b;
            }
            return count == 0 ? -1 : count;
        }

        @Override
        public void close() {
            // Do not close the delegate
        }

    }

}
