package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the vcsRoot with id = 'VersionedSettings'
from your code, and delete the patch script.
*/
deleteVcsRoot(RelativeId("VersionedSettings"))

