package org.gradle.profiler.heapdump.agent;

import org.gradle.profiler.heapdump.agent.writers.CsvWriter;
import org.gradle.profiler.heapdump.agent.writers.HprofWriter;
import org.gradle.profiler.heapdump.agent.writers.TxtWriter;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates heap dumps at specific points in the Gradle build lifecycle.
 * Uses composition with HeapDumpStrategy to determine when and how to intercept.
 */
// IDEA will mark this class as unused, but it is in fact used by the generated bytecode done in HeapDumpAgent
@SuppressWarnings("unused")
public class HeapDumpExecutor {

    private static int heapDumpCounter = 1;

    public static void invoke(String directory, String strategy, String additionalData) {
        try {
            long pid = ProcessHandle.current().pid();

            Path dirPath = Path.of(directory).toAbsolutePath();
            // Create output directory if it doesn't exist
            Files.createDirectories(dirPath);

            // Generate base filename with PID, sequential number and strategy
            String baseFilename = pid + "-" + heapDumpCounter + "-" + strategy;

            // Create heap dump
            HprofWriter.write(dirPath, baseFilename);
            // Write heap statistics to companion file
            TxtWriter.write(dirPath, baseFilename, heapDumpCounter, strategy, additionalData, pid);
            // Append CSV data for analysis
            CsvWriter.write(dirPath, baseFilename, heapDumpCounter, strategy, additionalData, pid);
        } catch (Exception e) {
            System.err.println("HEAP_DUMP_EXECUTOR: Failed to create heap dump: " + e.getMessage());
            e.printStackTrace();
        } finally {
            heapDumpCounter++;
        }
    }

}
