package org.gradle.profiler.heapdump.agent;

import com.sun.management.HotSpotDiagnosticMXBean;

import javax.management.MBeanServer;
import java.io.File;
import java.lang.management.ManagementFactory;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates heap dumps at specific points in the Gradle build lifecycle.
 * Uses composition with HeapDumpStrategy to determine when and how to intercept.
 */
// IDEA will mark this class as unused, but it is in fact used by the generated bytecode done in HeapDumpAgent
@SuppressWarnings("unused")
public class HeapDumpExecutor {

    public static void invoke(String outputDir, String strategyName) {
        // Generate unique filename with timestamp
        String timestamp = String.valueOf(System.currentTimeMillis());
        String filename = "gradle-" + strategyName + "-" + timestamp + ".hprof";
        String fullPath = new File(outputDir, filename).getAbsolutePath();

        System.out.println("HEAP_DUMP_EXECUTOR: Creating heap dump at " + fullPath);
        try {
            // Create output directory if it doesn't exist
            Files.createDirectories(Path.of(outputDir));

            MBeanServer server = ManagementFactory.getPlatformMBeanServer();
            HotSpotDiagnosticMXBean mxBean = ManagementFactory.newPlatformMXBeanProxy(
                server,
                "com.sun.management:type=HotSpotDiagnostic",
                HotSpotDiagnosticMXBean.class
            );
            mxBean.dumpHeap(fullPath, true);
            System.out.println("HEAP_DUMP_EXECUTOR: Heap dump created successfully");
        } catch (Exception e) {
            System.err.println("HEAP_DUMP_EXECUTOR: Failed to create heap dump: " + e.getMessage());
            e.printStackTrace();
        }
    }

}
