package org.gradle.profiler.heapdump.agent;

import com.sun.management.HotSpotDiagnosticMXBean;

import javax.management.MBeanServer;
import java.lang.management.ManagementFactory;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates heap dumps at specific points in the Gradle build lifecycle.
 * Uses composition with HeapDumpStrategy to determine when and how to intercept.
 */
// IDEA will mark this class as unused, but it is in fact used by the generated bytecode done in HeapDumpAgent
@SuppressWarnings("unused")
public class HeapDumpExecutor {

    public static void invoke(String directory, String strategy) {
        try {
            long pid = ProcessHandle.current().pid();
            // Create output directory if it doesn't exist
            Path dirPath = Path.of(directory);
            Files.createDirectories(dirPath);

            // Generate unique filename with PID and optional sequential number
            String filename = generateUniqueFilename(dirPath, strategy, pid);
            Path filePath = dirPath.resolve(filename);

            System.out.println("HEAP_DUMP_EXECUTOR: Creating heap dump at " + filePath);

            MBeanServer server = ManagementFactory.getPlatformMBeanServer();
            HotSpotDiagnosticMXBean mxBean = ManagementFactory.newPlatformMXBeanProxy(
                server,
                "com.sun.management:type=HotSpotDiagnostic",
                HotSpotDiagnosticMXBean.class
            );
            mxBean.dumpHeap(filePath.toString(), true);
            System.out.println("HEAP_DUMP_EXECUTOR: Heap dump created successfully");
        } catch (Exception e) {
            System.err.println("HEAP_DUMP_EXECUTOR: Failed to create heap dump: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static String generateUniqueFilename(Path directory, String strategy, long pid) {
        // Try base filename first: heapdump-<strategy>-<pid>.hprof
        String baseFilename = "heapdump-" + strategy + "-" + pid + ".hprof";
        Path basePath = directory.resolve(baseFilename);

        if (!Files.exists(basePath)) {
            return baseFilename;
        }

        // If base filename exists, try with sequential numbers
        int sequence = 1;
        while (true) {
            String filename = "heapdump-" + strategy + "-" + pid + "-" + sequence + ".hprof";
            Path path = directory.resolve(filename);
            if (!Files.exists(path)) {
                return filename;
            }
            sequence++;
        }
    }

}
