#
# Copyright 2026 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('pre', 'post')]
    [string]$Phase
)

$ErrorActionPreference = 'Stop'

$GeneratedByPreBuild = 'Generated by the TeamCity agent pre-build hook'
$MavenMirrorProperty = 'org.gradle.mirror.maven.settings=true'
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Get-MirrorUrl([string]$Name) {
    if (-not $env:REPO_MIRROR_URLS) { return '' }
    foreach ($entry in $env:REPO_MIRROR_URLS.Split(',')) {
        $separator = $entry.IndexOf(':')
        if ($separator -gt 0 -and $entry.Substring(0, $separator) -eq $Name) {
            return $entry.Substring($separator + 1)
        }
    }
    return ''
}

function Get-MirrorXml([string]$Id, [string]$MirrorOf, [string]$Url) {
    if ($Url) {
        return "    <mirror><id>$Id</id><mirrorOf>$MirrorOf</mirrorOf><url>$Url</url></mirror>"
    }
    return $null
}

function Remove-GeneratedMavenMirrors([string]$MavenSettings, [string]$GradleUserHome) {
    if ((Test-Path -LiteralPath $MavenSettings -PathType Leaf) -and
        ([IO.File]::ReadAllText($MavenSettings).Contains($GeneratedByPreBuild))) {
        Write-Output "Removing $MavenSettings generated by pre-build"
        Remove-Item -LiteralPath $MavenSettings -Force
    }

    $gradleProperties = Join-Path $GradleUserHome 'gradle.properties'
    if (-not (Test-Path -LiteralPath $gradleProperties -PathType Leaf)) { return }

    $marker = "# $GeneratedByPreBuild"
    $lines = [IO.File]::ReadAllLines($gradleProperties)
    if ($lines -notcontains $marker) { return }

    $kept = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $lines.Length; $i++) {
        if ($lines[$i] -eq $marker -and ($i + 1) -lt $lines.Length -and $lines[$i + 1] -eq $MavenMirrorProperty) {
            $i++
            continue
        }
        $kept.Add($lines[$i])
    }
    $content = ''
    if ($kept.Count -gt 0) { $content = ($kept -join "`r`n") + "`r`n" }
    [IO.File]::WriteAllText($gradleProperties, $content, $Utf8NoBom)
}

function Add-MavenMirrors([string]$MavenSettings, [string]$GradleUserHome) {
    Remove-GeneratedMavenMirrors $MavenSettings $GradleUserHome

    if (Test-Path -LiteralPath $MavenSettings) {
        Write-Output "$MavenSettings was not generated by pre-build, leaving it alone and not provisioning mirrors"
        return
    }

    if ($env:IGNORE_MIRROR -eq 'true' -or -not $env:REPO_MIRROR_URLS) {
        Write-Output "Repository mirrors disabled, not provisioning $MavenSettings"
        return
    }

    $mirrors = @(
        (Get-MirrorXml 'grdev-central' 'central' (Get-MirrorUrl 'mavencentral')),
        (Get-MirrorXml 'grdev-plugin-portal' 'Gradle Central Plugin Repository' (Get-MirrorUrl 'gradle-prod-plugins')),
        (Get-MirrorXml 'grdev-google' 'Google,google' (Get-MirrorUrl 'google'))
    ) | Where-Object { $_ }
    if (-not $mirrors) {
        Write-Output "REPO_MIRROR_URLS has no mirror for Maven Central, the Plugin Portal or Google, not provisioning $MavenSettings"
        return
    }

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $MavenSettings) | Out-Null
    New-Item -ItemType Directory -Force -Path $GradleUserHome | Out-Null

    $settings = @("<!-- $GeneratedByPreBuild -->", '<settings>', '  <mirrors>') + $mirrors + @('  </mirrors>', '</settings>')
    [IO.File]::WriteAllText($MavenSettings, ($settings -join "`r`n") + "`r`n", $Utf8NoBom)

    $gradleProperties = Join-Path $GradleUserHome 'gradle.properties'
    $prefix = ''
    if (Test-Path -LiteralPath $gradleProperties -PathType Leaf) {
        $existing = [IO.File]::ReadAllText($gradleProperties)
        if ($existing.Length -gt 0 -and -not $existing.EndsWith("`n")) { $prefix = "`r`n" }
    }
    [IO.File]::AppendAllText($gradleProperties, "$prefix# $GeneratedByPreBuild`r`n$MavenMirrorProperty`r`n", $Utf8NoBom)

    Write-Output "Provisioned ${MavenSettings}:"
    Get-Content -LiteralPath $MavenSettings
}

$mavenSettings = Join-Path (Join-Path $env:USERPROFILE '.m2') 'settings.xml'
$gradleUserHome = $env:GRADLE_USER_HOME
if (-not $gradleUserHome) { $gradleUserHome = Join-Path $env:USERPROFILE '.gradle' }

if ($Phase -eq 'pre') {
    Add-MavenMirrors $mavenSettings $gradleUserHome
} else {
    Remove-GeneratedMavenMirrors $mavenSettings $gradleUserHome
}
