#!/bin/bash
#
# Copyright 2026 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

GENERATED_BY_PRE_BUILD="Generated by the TeamCity agent pre-build hook"
MAVEN_MIRROR_PROPERTY="org.gradle.mirror.maven.settings=true"

function mirrorUrl() {
  local name="$1"
  local entry
  local IFS=','
  for entry in ${REPO_MIRROR_URLS:-}; do
    if [ "${entry%%:*}" = "${name}" ]; then
      echo "${entry#*:}"
      return 0
    fi
  done
}

function mirrorXml() {
  local id="$1"
  local mirrorOf="$2"
  local url="$3"
  if [ -n "${url}" ]; then
    echo "    <mirror><id>${id}</id><mirrorOf>${mirrorOf}</mirrorOf><url>${url}</url></mirror>"
  fi
}

function removeGeneratedMavenMirrors() {
  local mavenSettings="$1"
  local gradleProperties="$2/gradle.properties"

  if [ -f "${mavenSettings}" ] && grep -qF "${GENERATED_BY_PRE_BUILD}" "${mavenSettings}"; then
    echo "Removing ${mavenSettings} generated by pre-build"
    rm -f "${mavenSettings}"
  fi

  if [ -f "${gradleProperties}" ] && grep -qxF "# ${GENERATED_BY_PRE_BUILD}" "${gradleProperties}"; then
    local filtered
    filtered="$(mktemp "${gradleProperties}.XXXXXX")"
    awk -v marker="# ${GENERATED_BY_PRE_BUILD}" -v property="${MAVEN_MIRROR_PROPERTY}" '
      {
        if (pending) {
          pending = 0
          if ($0 == property) next
          print held
        }
        if ($0 == marker) { held = $0; pending = 1; next }
        print
      }
      END { if (pending) print held }
    ' "${gradleProperties}" > "${filtered}"
    mv "${filtered}" "${gradleProperties}"
  fi
}

function provisionMavenMirrors() {
  local mavenSettings="$1"
  local gradleUserHome="$2"
  local gradleProperties="${gradleUserHome}/gradle.properties"

  removeGeneratedMavenMirrors "${mavenSettings}" "${gradleUserHome}"

  if [ -f "${mavenSettings}" ]; then
    echo "${mavenSettings} was not generated by pre-build, leaving it alone and not provisioning mirrors"
    return 0
  fi

  if [ "${IGNORE_MIRROR:-false}" = "true" ] || [ -z "${REPO_MIRROR_URLS:-}" ]; then
    echo "Repository mirrors disabled, not provisioning ${mavenSettings}"
    return 0
  fi

  local mirrors
  mirrors="$(
    mirrorXml grdev-central "central" "$(mirrorUrl mavencentral)"
    mirrorXml grdev-plugin-portal "Gradle Central Plugin Repository" "$(mirrorUrl gradle-prod-plugins)"
    mirrorXml grdev-google "Google,google" "$(mirrorUrl google)"
  )"
  if [ -z "${mirrors}" ]; then
    echo "REPO_MIRROR_URLS has no mirror for Maven Central, the Plugin Portal or Google, not provisioning ${mavenSettings}"
    return 0
  fi

  mkdir -p "$(dirname "${mavenSettings}")" "${gradleUserHome}"
  cat > "${mavenSettings}" <<EOF
<!-- ${GENERATED_BY_PRE_BUILD} -->
<settings>
  <mirrors>
${mirrors}
  </mirrors>
</settings>
EOF
  if [ -s "${gradleProperties}" ] && [ -n "$(tail -c 1 "${gradleProperties}")" ]; then
    echo >> "${gradleProperties}"
  fi
  printf '# %s\n%s\n' "${GENERATED_BY_PRE_BUILD}" "${MAVEN_MIRROR_PROPERTY}" >> "${gradleProperties}"
  echo "Provisioned ${mavenSettings}:"
  cat "${mavenSettings}"
}
