name: Update jdks.yaml

on:
  workflow_dispatch: # Allows manual triggering of the action
  schedule: # Runs the action weekly on Monday at 3:42 UTC
    - cron: '42 3 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-jdks:
    if: github.repository == 'gradle/gradle-profiler'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update jdks.yaml
        uses: gradle/update-jdks-action@main
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          signoff: true
          sign-commits: true
          commit-message: "Update jdks.yaml"
          add-paths: .teamcity/jdks.yaml
          title: "Update jdks.yaml"
          body: "This PR updates JDK to the latest versions available in `.teamcity/jdks.yaml`."
          delete-branch: true
          branch: "devprod/update-jdks"
          branch-suffix: timestamp
          labels: |
            @dev-productivity
            no-changelog
